services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    env_file:
      - .env
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config-homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: gethomepage.dev # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /config-homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      TZ: Europe/Amsterdam

  jellyfin:
    image: jellyfin/jellyfin:2026061922
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - /config-jellyfin:/config
      - ${MEDIA_PATH}:/media
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    ports:
      - "32400:32400"
    environment:
      - TZ=America/Sao_Paulo
      - PLEX_CLAIM=your_claim_token
    volumes:
      - /config-plex:/config
      - ${MEDIA_PATH}:/data
